Feature/board paging
Fast-Side/Fast-Blog pull request #4
Opened 2023-09-15 11:38 UTC by tjdtn0219

* 메인 화면 변경 (메인 화면에 있는 게시글 목록은 페이징 적용X)
* 게시글 목록 : 페이징 적용

2023-09-17 07:15 UTC, tkddn204 requested changes

2023-09-17 07:15 UTC, tkddn204 approved these changes

2023-09-17 08:18 UTC, merged

2023-09-18 03:26 UTC, cyPark95 reviewed
고생하셨습니다!
EOF 관련해서 코멘트 남겼습니다!

2023-09-18 03:26 UTC, cyPark95 commented on src/main/resources/application-dev.yml
> +  width: 3
마지막에 개행문자 넣어주시면 좋을것 같습니다!

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
참고해보시면 좋을것 같아요!